### ISSUE TITLE
perf: consider using solmate for transfers

### ISSUE THREAD

**Issue by transmissions11** [primitivefinance/rmm-core#255]
if you decide to, assign me to this issue and i'll open up a PR @Alexangelj :)

**Comment by Alexangelj** [comment]
The core doesn't have eth transfers or implemented tokens, so no place to utilize them.

We can in the periphery.

**Comment by transmissions11** [comment]
https://github.com/primitivefinance/rmm-core/blob/35820b518d9b452c84e415a84232e4de4299ef13/contracts/PrimitiveEngine.sol#L229

you sure?

**Comment by Alexangelj** [comment]
oh duh
