### ISSUE TITLE
perf: investigate use of storage and memory structs vs raw reads

### ISSUE THREAD

**Issue by transmissions11** [primitivefinance/rmm-core#256]
ie here: https://github.com/primitivefinance/rmm-core/blob/2b471d921fed27b9decf689e623458958ee872be/contracts/PrimitiveEngine.sol#L407

and here: https://github.com/primitivefinance/rmm-core/blob/2b471d921fed27b9decf689e623458958ee872be/contracts/PrimitiveEngine.sol#L133

**Comment by Alexangelj** [comment]
cc @clemlak let's investigate using gas tool
